services:
  backend:
    image: registry.cn-hangzhou.aliyuncs.com/wjn0918/soft:easybd-backend
    ports:
      - "5001:5001"
    networks:
      - easybd-network

  frontend:
    image: registry.cn-hangzhou.aliyuncs.com/wjn0918/soft:easybd-frontend
    ports:
      - "3000:80"
    networks:
      - easybd-network
    depends_on:
      - backend

networks:
  easybd-network:
    driver: bridge
