name: Build and Deploy web2

on:
  push:
    branches:
      - main  # 或你自己的部署分支

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Alibaba Cloud Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASS }}

      - name: Build Docker Images via Compose
        run: |
          docker compose -f compose_build_web2_action.yml build

      - name: Tag and Push Frontend Image
        run: |
          docker push registry.cn-hangzhou.aliyuncs.com/wjn0918/soft:easybd-web

      - name: Tag and Push Backend Image
        run: |
          docker push registry.cn-hangzhou.aliyuncs.com/wjn0918/soft:easybd-backend

  remote-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull registry.cn-hangzhou.aliyuncs.com/wjn0918/soft:easybd-web
            docker pull registry.cn-hangzhou.aliyuncs.com/wjn0918/soft:easybd-backend
            docker compose -f /opt/easybd/compose.yml down
            docker compose -f /opt/easybd/compose.yml up -d
